---
- name: set internal vars for generic Java version
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b{{ java_build }}"
  when: jdk_version_detail is not defined and java_build is defined

- name: compose filename, if necessary
  set_fact:
    jdk_tarball_file: "jdk-{{ java_version }}u{{ java_subversion }}-{{ jdk_os }}-{{ jdk_arch }}"
  when: jdk_tarball_file is not defined

- name: compose url for downloading file, if necessary
  set_fact:
    jdk_tarball_url:  "http://download.oracle.com/otn-pub/java/jdk/{{ jdk_version_detail }}/{{ jdk_tarball_file }}"
  when: jdk_version_detail is defined

- name: get JDK tarball (as tar.gz file)
  get_url:
    url: "{{ jdk_tarball_url }}.tar.gz"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
    checksum: md5:{{ java_checksum }}

- name: Create {{base_dir}}/java-versions folder
  file: path="{{base_dir}}/java-versions" state=directory
  become: true

- name: Unpack "{{ jdk_tarball_file }}.tar.gz" on {{base_dir}}/java-versions Prepare Java
  command: tar xvzf  "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz" -C  "{{base_dir}}/java-versions/"
  become: true